name: Deploy Dynamic App

on:
  push:
    branches: [main]
    paths:
      - 'dynamic-app/**'
      - 'database/**'
      - 'nginx/**'
      - 'docker-compose.yml'
      - '.github/workflows/deploy-dynamic.yml'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push dynamic image
        uses: docker/build-push-action@v6
        with:
          context: ./dynamic-app
          push: true
          tags: ${{ secrets.DYNAMIC_IMAGE }}

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/uas-adm
            docker compose pull dynamic-app
            docker compose up -d database dynamic-app nginx
